name: Emergens-env
channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - numpy=1.26
  - pandas=2.2
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - pyyaml
  - requests
  - tqdm
  - pytest

  - pip:
      - python-dotenv
      # tambahkan package pip lain di sini
