name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
          environment-file: environment.yml
          activate-environment: project-env
          auto-activate-base: false
          conda-remove-defaults: true   # penting: hapus channel defaults

      - name: Cek environment
        shell: bash -el {0}
        run: |
          conda info
          conda list
          python --version

      - name: Jalankan test
        shell: bash -el {0}
        run: |
          pytest -v
